OA_GOOGLE_CLIENT_ID: 924866628504-8to1f8cgfk1ooiap6uft54cvnu3nmgth.apps.googleusercontent.com
OA_GOOGLE_SECRET_KEY: AeBMrEfKswUjo-41RyQvBhLU
OA_GITHUB_CLIENT_ID: 123fd721dba1c9fc028e
OA_GITHUB_SECRET_KEY: 3dc78fb2552fcb77b01adf0e3f8864fcbfc60435